name: CD - Livraison Officielle

on:
  push:
    tags:
      - 'v*'

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write 

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Compilation de production ARMv7 (Debian Buster)
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          distro: buster
          run: |
            export DEBIAN_FRONTEND=noninteractive
            
            echo "deb http://archive.debian.org/debian buster main" > /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list
            
            apt-get -o Acquire::Check-Valid-Until=false update -y
            apt-get install -y --allow-unauthenticated \
              build-essential \
              qtbase5-dev \
              qtbase5-private-dev \
              qtbase5-dev-tools \
              qt5-qmake \
              qtdeclarative5-dev \
              libqt5charts5-dev \
              git

            # 1. Compilation de la bibliothèque MQTT
            git clone https://github.com/qt/qtmqtt.git
            cd qtmqtt
            git checkout 5.11
            /usr/lib/qt5/bin/qmake
            make
            make install
            cd ..

            # 2. Compilation de ton projet EcurieActive
            /usr/lib/qt5/bin/qmake
            make

            # 3. EXTRACTION DES FICHIERS
            echo "Extraction de la bibliotheque MQTT pour la Release..."
            # On utilise -P pour bien copier les liens symboliques tels quels
            cp -P qtmqtt/lib/libQt5Mqtt.so.5* .
            
            # On verifie ce qu'on a extrait pour le log GitHub
            ls -lh libQt5Mqtt.so.5*

      - name: Publication de la Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Version ${{ github.ref_name }}
          # On demande à GitHub de prendre l'exécutable ET les fichiers libQt5Mqtt
          files: |
            EcurieActiveNabou
            libQt5Mqtt.so.5*
          generate_release_notes: true
          body: |
            Release automatisee pour architecture ARMv7 (Raspberry Pi OS Legacy).
            ID de compilation : ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}